version: '3'

services:
  app: 
    image: boogoo-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/base/pages
      - ./public:/base/public
      - ./styles:/base/styles
      - ./components:/base/components
